### ISSUE TITLE
Basic startup question using Javascript

### ISSUE THREAD

**Issue by chriswill** [ergoplatform/ergo-appkit#112]
I've completed the basic startup configuration and verified that my GraalVM is successfully installed.  I'm using GraalVM CE 19.3.6, which has the openjdk 11.0.11.  I'm using the current appkit 2.12-04.0.5 file which I installed from the published version.  I'm on Ubuntu 20.0.4.

I have a simple script that I've cut down from FreezeCoin.js:
```
const Integer = Java.type("java.lang.Integer")
const Long = Java.type("java.lang.Long")
const Address = Java.type("org.ergoplatform.appkit.Address")
const RestApiErgoClient = Java.type("org.ergoplatform.appkit.RestApiErgoClient")
const ErgoClientException = Java.type("org.ergoplatform.appkit.ErgoClientException")
const ConstantsBuilder = Java.type("org.ergoplatform.appkit.ConstantsBuilder")
const ErgoToolConfig = Java.type("org.ergoplatform.appkit.config.ErgoToolConfig")
const Parameters = Java.type("org.ergoplatform.appkit.Parameters")

const conf = ErgoToolConfig.load("freeze_coin_config.json");
```

When I run this with the command line: js --jvm --vm.cp=target/ergo-appkit_2.12-4.0.5.jar examples/test.js

I get the following error:
`java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
        at org.ergoplatform.appkit.config.ErgoToolConfig.load(ErgoToolConfig.java:53)
        at org.ergoplatform.appkit.config.ErgoToolConfig.load(ErgoToolConfig.java:67)
        at <js> :program(examples/test.js:10:557-590)`

My config file is present in the directory.  Any suggestions on how to resolve?

**Comment by aslesarenko** [comment]
You probably need to generate a fat jar file using `sbt assembly` command.

**Comment by chriswill** [comment]
lol, yes that jar now needs to go on a diet!  It's like 100x the size of the release version.  But the script does now run.  Thanks for the help.
