### ISSUE TITLE
Offset and limit parameters are switched around

### ISSUE THREAD

**Issue by Luivatra** [ergoplatform/ergo-appkit#228]
https://github.com/ergoplatform/ergo-appkit/blob/580452799fb5d7dfeeb1bda28803042928f16a3a/lib-impl/src/main/java/org/ergoplatform/appkit/impl/NodeDataSourceImpl.java#L221

**Comment by MrStahlfelge** [comment]
If you provide a PR we can merge it very fast :)

**Comment by Luivatra** [comment]
> If you provide a PR we can merge it very fast :)

morphic already fixed it, using a snapshot with the fix

**Comment by MrStahlfelge** [comment]
So this could get closed?
