### ISSUE TITLE
toJson method in SignedTransaction seems to have problems.

### ISSUE THREAD

**Issue by mehranagh20** [ergoplatform/ergo-appkit#27]
In case setting prettyPrint to true, "ergoTree"  parameter of boxes in the transaction has a problem like the below example:

`{
      "ergoTree": "ErgoTree(0,WrappedArray(),Right(ConstantNode(SigmaProp(ProveDlog(ECPoint(4a186c,125e7c,...))),SSigmaProp)),80,[B@73d60e76)",
    }`

**Comment by aslesarenko** [comment]
@mehranagh20 the ErgoTree here is printed using toString method. So it is not something that can be parsed back. Setting prettyPrint = false, will output Base16 string for "ergoTree", but the json will not be formatted. 

The solution is to add `formatJson` option.

**Comment by mehranagh20** [comment]
@aslesarenko Right, setting prettyPrint to false solves the problem; afterward, I used Gson with pretty printing to prettify it.
Maybe the same can be done in the toJson method.
