### ISSUE TITLE
Replace BoxOperation.selectTop implementation with ergo wallet's BoxSelector

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/ergo-appkit#37]
http://github.com/ergoplatform/ergo/blob/b2de36c3684d4044b9608a0f928f1338fc55e9bb/ergo-wallet/src/main/scala/org/ergoplatform/wallet/boxes/BoxSelector.scala#L9-L73

**Comment by MrStahlfelge** [comment]
The linked method is already used by BoxOperation.selectTop as the last step. What should be changed in your opinion @greenhat ?

**Comment by greenhat** [comment]
Yes, it's using ergo-wallet's box selector now. I believe it was not the case when I created this issue. I'm closing it.
