### ISSUE TITLE
It's not possible to create transaction without change.

### ISSUE THREAD

**Issue by mehranagh20** [ergoplatform/ergo-appkit#52]
If provided inputs and outputs happen to have the same amount of erg then tx builder fails because apparently it can not create change box.

**Comment by mehranagh20** [comment]
This issue is related to #51. Generally, it is possible to create a transaction without change but if there are some leftover tokens which it tries to put in change address it may fail.

**Comment by MrStahlfelge** [comment]
I think we can close this one. It is possible to have a tx without change.

However, there are edge cases in which box selection could be improved. At the moment, Appkit always prefers the first box loaded. If the amount of ERG matches exactly but there are token that need to be changed, it would be better to select another box. But that is another issue.
