### ISSUE TITLE
explorer.api not fitting current scheme, needs to be refreshed

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo-appkit#80]
I tried to execute some methods in `AddressesApi` without success:

* `addressesIdGet`: Failed because `FullAddressTransactions` declares integers, but longs are coming
* `addressesIdTransactionsGet`: Failed because it should return `List<Transaction>` but api call wraps the list

Looks like the wrappers need to be refreshed.

As a suggestion, maybe this should be extracted to an own lib. This way, it could get updated or changed without the need to update appkit itself.

**Comment by aslesarenko** [comment]
@MrStahlfelge I don't know what is the right way to implement REST wrappers this days in Java? I'm not sure the library I used it the right one for the job.

**Comment by MrStahlfelge** [comment]
I am sharing your objections regarding reflection, but there is no problem doing so. Retrofit and Gson are widely used on Android, so this way is good to go.

**Comment by aslesarenko** [comment]
Resolved in #83
