### ISSUE TITLE
Add way to find out what went wrong when sendTransaction fails

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo-appkit#85]
`BlockChainContext.sendTransaction` returns `null` or an empty string if no transaction could be made. However, it would be good to let the calling application know what went wrong. This could be done by throwing an error containing Retrofit's call object with more information.

**Comment by aslesarenko** [comment]
The transaction is made before calling this method. The method just sends the transaction to the node. If the sending fails, the exception is raised.  Or am I missing something?

**Comment by MrStahlfelge** [comment]
Closed because I am using `BoxOperations.send` now without problems
