### ISSUE TITLE
BlockChainContext.sendTransaction returns txId with quotes

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo-appkit#86]
When calling `BlockChainContext.sendTransaction`, the transaction id is returned with quotes. It would be better if the txId is returned without quotes.

**Comment by MrStahlfelge** [comment]
I solved this now by using BoxOperations.send. However, I think it is not good that BoxOperations.send returns a json that I need to parse to get the transaction Id. Do you think we could change this to return the SignedTransaction object?

**Comment by aslesarenko** [comment]
@MrStahlfelge just checked, there is no quotes returned.

**Comment by MrStahlfelge** [comment]
Closed because I am using BoxOperations.send now without problems
