### ISSUE TITLE
Create EIP-3 compliant addresses

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/ergo-appkit#87]
Current method Address.fromMnemonic is not [EIP-3](https://github.com/ergoplatform/eips/blob/master/eip-0003.md) compliant.

A new method Address.fromMnemonicEip3 needs to be created to support generation of EIP3 compliant first address.

**Comment by MrStahlfelge** [comment]
Would be great if you can add option to derive the next addresses as well when working on it. :+1:
