### ISSUE TITLE
mistake condition for set explorerUrl

### ISSUE THREAD

**Issue by zargarzadehm** [ergoplatform/ergo-appkit#94]
https://github.com/ergoplatform/ergo-appkit/blob/271d4122f8edb78ad37a5b54c5cc2e0c22877ec2/appkit/src/main/java/org/ergoplatform/appkit/RestApiErgoClient.java#L42

This condition is not True, this condition is true in not mode

**Comment by MrStahlfelge** [comment]
Thanks for the fix!
